//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("net", Namespace="", IsNullable=false)]
public partial class netType {
    
    private locationType locationField;
    
    private typeType[] typeField;
    
    private edgeType[] edgeField;
    
    private tlLogicType[] tlLogicField;
    
    private junctionType[] junctionField;
    
    private connectionType[] connectionField;
    
    private prohibitionType[] prohibitionField;
    
    private roundaboutType[] roundaboutField;
    
    private tazType[] tazField;
    
    private string versionField;
    
    private int junctionCornerDetailField;
    
    private bool junctionCornerDetailFieldSpecified;
    
    private int junctionLinkDetailField;
    
    private bool junctionLinkDetailFieldSpecified;
    
    private boolType lefthandField;
    
    private bool lefthandFieldSpecified;
    
    private boolType rectangularLaneCutField;
    
    private bool rectangularLaneCutFieldSpecified;
    
    private boolType walkingareasField;
    
    private bool walkingareasFieldSpecified;
    
    private string limitTurnSpeedField;
    
    private boolType checkLaneFoesAllField;
    
    private bool checkLaneFoesAllFieldSpecified;
    
    private boolType checkLaneFoesRoundaboutField;
    
    private bool checkLaneFoesRoundaboutFieldSpecified;
    
    private boolType tlsIgnoreInternalJunctionJamField;
    
    private bool tlsIgnoreInternalJunctionJamFieldSpecified;
    
    private spreadTypeType spreadTypeField;
    
    private bool spreadTypeFieldSpecified;
    
    private boolType avoidOverlapField;
    
    private bool avoidOverlapFieldSpecified;
    
    private boolType junctionHigherSpeedField;
    
    private bool junctionHigherSpeedFieldSpecified;
    
    private string internalJunctionsVehicleWidthField;
    
    /// <remarks/>
    public locationType location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("type")]
    public typeType[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("edge")]
    public edgeType[] edge {
        get {
            return this.edgeField;
        }
        set {
            this.edgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tlLogic")]
    public tlLogicType[] tlLogic {
        get {
            return this.tlLogicField;
        }
        set {
            this.tlLogicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("junction")]
    public junctionType[] junction {
        get {
            return this.junctionField;
        }
        set {
            this.junctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection")]
    public connectionType[] connection {
        get {
            return this.connectionField;
        }
        set {
            this.connectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("prohibition")]
    public prohibitionType[] prohibition {
        get {
            return this.prohibitionField;
        }
        set {
            this.prohibitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("roundabout")]
    public roundaboutType[] roundabout {
        get {
            return this.roundaboutField;
        }
        set {
            this.roundaboutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("taz")]
    public tazType[] taz {
        get {
            return this.tazField;
        }
        set {
            this.tazField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int junctionCornerDetail {
        get {
            return this.junctionCornerDetailField;
        }
        set {
            this.junctionCornerDetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool junctionCornerDetailSpecified {
        get {
            return this.junctionCornerDetailFieldSpecified;
        }
        set {
            this.junctionCornerDetailFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int junctionLinkDetail {
        get {
            return this.junctionLinkDetailField;
        }
        set {
            this.junctionLinkDetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool junctionLinkDetailSpecified {
        get {
            return this.junctionLinkDetailFieldSpecified;
        }
        set {
            this.junctionLinkDetailFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType lefthand {
        get {
            return this.lefthandField;
        }
        set {
            this.lefthandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lefthandSpecified {
        get {
            return this.lefthandFieldSpecified;
        }
        set {
            this.lefthandFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType rectangularLaneCut {
        get {
            return this.rectangularLaneCutField;
        }
        set {
            this.rectangularLaneCutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rectangularLaneCutSpecified {
        get {
            return this.rectangularLaneCutFieldSpecified;
        }
        set {
            this.rectangularLaneCutFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType walkingareas {
        get {
            return this.walkingareasField;
        }
        set {
            this.walkingareasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool walkingareasSpecified {
        get {
            return this.walkingareasFieldSpecified;
        }
        set {
            this.walkingareasFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string limitTurnSpeed {
        get {
            return this.limitTurnSpeedField;
        }
        set {
            this.limitTurnSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType checkLaneFoesAll {
        get {
            return this.checkLaneFoesAllField;
        }
        set {
            this.checkLaneFoesAllField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool checkLaneFoesAllSpecified {
        get {
            return this.checkLaneFoesAllFieldSpecified;
        }
        set {
            this.checkLaneFoesAllFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType checkLaneFoesRoundabout {
        get {
            return this.checkLaneFoesRoundaboutField;
        }
        set {
            this.checkLaneFoesRoundaboutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool checkLaneFoesRoundaboutSpecified {
        get {
            return this.checkLaneFoesRoundaboutFieldSpecified;
        }
        set {
            this.checkLaneFoesRoundaboutFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType tlsIgnoreInternalJunctionJam {
        get {
            return this.tlsIgnoreInternalJunctionJamField;
        }
        set {
            this.tlsIgnoreInternalJunctionJamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tlsIgnoreInternalJunctionJamSpecified {
        get {
            return this.tlsIgnoreInternalJunctionJamFieldSpecified;
        }
        set {
            this.tlsIgnoreInternalJunctionJamFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public spreadTypeType spreadType {
        get {
            return this.spreadTypeField;
        }
        set {
            this.spreadTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool spreadTypeSpecified {
        get {
            return this.spreadTypeFieldSpecified;
        }
        set {
            this.spreadTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType avoidOverlap {
        get {
            return this.avoidOverlapField;
        }
        set {
            this.avoidOverlapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool avoidOverlapSpecified {
        get {
            return this.avoidOverlapFieldSpecified;
        }
        set {
            this.avoidOverlapFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType junctionHigherSpeed {
        get {
            return this.junctionHigherSpeedField;
        }
        set {
            this.junctionHigherSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool junctionHigherSpeedSpecified {
        get {
            return this.junctionHigherSpeedFieldSpecified;
        }
        set {
            this.junctionHigherSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string internalJunctionsVehicleWidth {
        get {
            return this.internalJunctionsVehicleWidthField;
        }
        set {
            this.internalJunctionsVehicleWidthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class locationType {
    
    private string netOffsetField;
    
    private string convBoundaryField;
    
    private string origBoundaryField;
    
    private string projParameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string netOffset {
        get {
            return this.netOffsetField;
        }
        set {
            this.netOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string convBoundary {
        get {
            return this.convBoundaryField;
        }
        set {
            this.convBoundaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string origBoundary {
        get {
            return this.origBoundaryField;
        }
        set {
            this.origBoundaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string projParameter {
        get {
            return this.projParameterField;
        }
        set {
            this.projParameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tazSubType {
    
    private string idField;
    
    private string weightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tazType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string idField;
    
    private string edgesField;
    
    private string shapeField;
    
    private string centerField;
    
    private boolType fillField;
    
    private bool fillFieldSpecified;
    
    private string colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(paramType))]
    [System.Xml.Serialization.XmlElementAttribute("tazSink", typeof(tazSubType))]
    [System.Xml.Serialization.XmlElementAttribute("tazSource", typeof(tazSubType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string edges {
        get {
            return this.edgesField;
        }
        set {
            this.edgesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string center {
        get {
            return this.centerField;
        }
        set {
            this.centerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType fill {
        get {
            return this.fillField;
        }
        set {
            this.fillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fillSpecified {
        get {
            return this.fillFieldSpecified;
        }
        set {
            this.fillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class paramType {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    param,
    
    /// <remarks/>
    tazSink,
    
    /// <remarks/>
    tazSource,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
public enum boolType {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
    
    /// <remarks/>
    True,
    
    /// <remarks/>
    False,
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    on,
    
    /// <remarks/>
    off,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    x,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("-")]
    Item,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class roundaboutType {
    
    private string nodesField;
    
    private string edgesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodes {
        get {
            return this.nodesField;
        }
        set {
            this.nodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string edges {
        get {
            return this.edgesField;
        }
        set {
            this.edgesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class prohibitionType {
    
    private string prohibitorField;
    
    private string prohibitedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prohibitor {
        get {
            return this.prohibitorField;
        }
        set {
            this.prohibitorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prohibited {
        get {
            return this.prohibitedField;
        }
        set {
            this.prohibitedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class conflictType {
    
    private string fromField;
    
    private string toField;
    
    private string fromLaneField;
    
    private string toLaneField;
    
    private string startPosField;
    
    private string endPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string fromLane {
        get {
            return this.fromLaneField;
        }
        set {
            this.fromLaneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string toLane {
        get {
            return this.toLaneField;
        }
        set {
            this.toLaneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startPos {
        get {
            return this.startPosField;
        }
        set {
            this.startPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string endPos {
        get {
            return this.endPosField;
        }
        set {
            this.endPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class connectionType {
    
    private object[] itemsField;
    
    private string fromField;
    
    private string toField;
    
    private string fromLaneField;
    
    private string toLaneField;
    
    private boolType passField;
    
    private bool passFieldSpecified;
    
    private boolType keepClearField;
    
    private bool keepClearFieldSpecified;
    
    private string contPosField;
    
    private string visibilityField;
    
    private string allowField;
    
    private string disallowField;
    
    private string speedField;
    
    private string lengthField;
    
    private string shapeField;
    
    private boolType uncontrolledField;
    
    private bool uncontrolledFieldSpecified;
    
    private string viaField;
    
    private string tlField;
    
    private string linkIndexField;
    
    private string linkIndex2Field;
    
    private string changeRightField;
    
    private string changeLeftField;
    
    private boolType indirectField;
    
    private bool indirectFieldSpecified;
    
    private string typeField;
    
    private connectionTypeDir dirField;
    
    private connectionTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("conflict", typeof(conflictType))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(paramType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string fromLane {
        get {
            return this.fromLaneField;
        }
        set {
            this.fromLaneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string toLane {
        get {
            return this.toLaneField;
        }
        set {
            this.toLaneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType pass {
        get {
            return this.passField;
        }
        set {
            this.passField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool passSpecified {
        get {
            return this.passFieldSpecified;
        }
        set {
            this.passFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType keepClear {
        get {
            return this.keepClearField;
        }
        set {
            this.keepClearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keepClearSpecified {
        get {
            return this.keepClearFieldSpecified;
        }
        set {
            this.keepClearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contPos {
        get {
            return this.contPosField;
        }
        set {
            this.contPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disallow {
        get {
            return this.disallowField;
        }
        set {
            this.disallowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType uncontrolled {
        get {
            return this.uncontrolledField;
        }
        set {
            this.uncontrolledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool uncontrolledSpecified {
        get {
            return this.uncontrolledFieldSpecified;
        }
        set {
            this.uncontrolledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string via {
        get {
            return this.viaField;
        }
        set {
            this.viaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tl {
        get {
            return this.tlField;
        }
        set {
            this.tlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string linkIndex {
        get {
            return this.linkIndexField;
        }
        set {
            this.linkIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string linkIndex2 {
        get {
            return this.linkIndex2Field;
        }
        set {
            this.linkIndex2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeRight {
        get {
            return this.changeRightField;
        }
        set {
            this.changeRightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeLeft {
        get {
            return this.changeLeftField;
        }
        set {
            this.changeLeftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType indirect {
        get {
            return this.indirectField;
        }
        set {
            this.indirectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indirectSpecified {
        get {
            return this.indirectFieldSpecified;
        }
        set {
            this.indirectFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectionTypeDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectionTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum connectionTypeDir {
    
    /// <remarks/>
    s,
    
    /// <remarks/>
    t,
    
    /// <remarks/>
    T,
    
    /// <remarks/>
    l,
    
    /// <remarks/>
    r,
    
    /// <remarks/>
    L,
    
    /// <remarks/>
    R,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum connectionTypeState {
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    m,
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    o,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("=")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("-")]
    Item1,
    
    /// <remarks/>
    s,
    
    /// <remarks/>
    w,
    
    /// <remarks/>
    Z,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class requestType {
    
    private string indexField;
    
    private string responseField;
    
    private string foesField;
    
    private boolType contField;
    
    private bool contFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string foes {
        get {
            return this.foesField;
        }
        set {
            this.foesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType cont {
        get {
            return this.contField;
        }
        set {
            this.contField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contSpecified {
        get {
            return this.contFieldSpecified;
        }
        set {
            this.contFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class junctionType {
    
    private requestType[] requestField;
    
    private paramType[] paramField;
    
    private string idField;
    
    private string xField;
    
    private string yField;
    
    private string zField;
    
    private junctionTypeType typeField;
    
    private string incLanesField;
    
    private string intLanesField;
    
    private string shapeField;
    
    private string nameField;
    
    private float radiusField;
    
    private bool radiusFieldSpecified;
    
    private boolType customShapeField;
    
    private bool customShapeFieldSpecified;
    
    private junctionTypeRightOfWay rightOfWayField;
    
    private bool rightOfWayFieldSpecified;
    
    private junctionTypeFringe fringeField;
    
    private bool fringeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("request")]
    public requestType[] request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("param")]
    public paramType[] param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public junctionTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string incLanes {
        get {
            return this.incLanesField;
        }
        set {
            this.incLanesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string intLanes {
        get {
            return this.intLanesField;
        }
        set {
            this.intLanesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusSpecified {
        get {
            return this.radiusFieldSpecified;
        }
        set {
            this.radiusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType customShape {
        get {
            return this.customShapeField;
        }
        set {
            this.customShapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool customShapeSpecified {
        get {
            return this.customShapeFieldSpecified;
        }
        set {
            this.customShapeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public junctionTypeRightOfWay rightOfWay {
        get {
            return this.rightOfWayField;
        }
        set {
            this.rightOfWayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rightOfWaySpecified {
        get {
            return this.rightOfWayFieldSpecified;
        }
        set {
            this.rightOfWayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public junctionTypeFringe fringe {
        get {
            return this.fringeField;
        }
        set {
            this.fringeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fringeSpecified {
        get {
            return this.fringeFieldSpecified;
        }
        set {
            this.fringeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum junctionTypeType {
    
    /// <remarks/>
    traffic_light,
    
    /// <remarks/>
    traffic_light_unregulated,
    
    /// <remarks/>
    traffic_light_right_on_red,
    
    /// <remarks/>
    rail_signal,
    
    /// <remarks/>
    rail_crossing,
    
    /// <remarks/>
    priority,
    
    /// <remarks/>
    priority_stop,
    
    /// <remarks/>
    left_before_right,
    
    /// <remarks/>
    right_before_left,
    
    /// <remarks/>
    allway_stop,
    
    /// <remarks/>
    zipper,
    
    /// <remarks/>
    district,
    
    /// <remarks/>
    unregulated,
    
    /// <remarks/>
    @internal,
    
    /// <remarks/>
    dead_end,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum junctionTypeRightOfWay {
    
    /// <remarks/>
    @default,
    
    /// <remarks/>
    mixedPriority,
    
    /// <remarks/>
    allwayStop,
    
    /// <remarks/>
    edgePriority,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum junctionTypeFringe {
    
    /// <remarks/>
    @default,
    
    /// <remarks/>
    outer,
    
    /// <remarks/>
    inner,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class functionType {
    
    private assignmentType[] itemsField;
    
    private string idField;
    
    private int nArgsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assignment")]
    public assignmentType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nArgs {
        get {
            return this.nArgsField;
        }
        set {
            this.nArgsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class assignmentType {
    
    private string idField;
    
    private string checkField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string check {
        get {
            return this.checkField;
        }
        set {
            this.checkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class conditionType {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class phaseType {
    
    private float durationField;
    
    private string minDurField;
    
    private string maxDurField;
    
    private string earliestEndField;
    
    private string latestEndField;
    
    private string earlyTargetField;
    
    private string finalTargetField;
    
    private float yellowField;
    
    private bool yellowFieldSpecified;
    
    private float redField;
    
    private bool redFieldSpecified;
    
    private float vehextField;
    
    private bool vehextFieldSpecified;
    
    private string stateField;
    
    private string nextField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minDur {
        get {
            return this.minDurField;
        }
        set {
            this.minDurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxDur {
        get {
            return this.maxDurField;
        }
        set {
            this.maxDurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string earliestEnd {
        get {
            return this.earliestEndField;
        }
        set {
            this.earliestEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latestEnd {
        get {
            return this.latestEndField;
        }
        set {
            this.latestEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string earlyTarget {
        get {
            return this.earlyTargetField;
        }
        set {
            this.earlyTargetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finalTarget {
        get {
            return this.finalTargetField;
        }
        set {
            this.finalTargetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float yellow {
        get {
            return this.yellowField;
        }
        set {
            this.yellowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool yellowSpecified {
        get {
            return this.yellowFieldSpecified;
        }
        set {
            this.yellowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float red {
        get {
            return this.redField;
        }
        set {
            this.redField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool redSpecified {
        get {
            return this.redFieldSpecified;
        }
        set {
            this.redFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float vehext {
        get {
            return this.vehextField;
        }
        set {
            this.vehextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vehextSpecified {
        get {
            return this.vehextFieldSpecified;
        }
        set {
            this.vehextFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tlLogicType {
    
    private object[] itemsField;
    
    private string idField;
    
    private tlTypeType typeField;
    
    private bool typeFieldSpecified;
    
    private string programIDField;
    
    private string offsetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assignment", typeof(assignmentType))]
    [System.Xml.Serialization.XmlElementAttribute("condition", typeof(conditionType))]
    [System.Xml.Serialization.XmlElementAttribute("function", typeof(functionType))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(paramType))]
    [System.Xml.Serialization.XmlElementAttribute("phase", typeof(phaseType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public tlTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string programID {
        get {
            return this.programIDField;
        }
        set {
            this.programIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
public enum tlTypeType {
    
    /// <remarks/>
    actuated,
    
    /// <remarks/>
    delay_based,
    
    /// <remarks/>
    @static,
    
    /// <remarks/>
    NEMA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class stopOffsetType {
    
    private float valueField;
    
    private string vClassesField;
    
    private string exceptionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vClasses {
        get {
            return this.vClassesField;
        }
        set {
            this.vClassesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string exceptions {
        get {
            return this.exceptionsField;
        }
        set {
            this.exceptionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class neighType {
    
    private string laneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lane {
        get {
            return this.laneField;
        }
        set {
            this.laneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class laneType {
    
    private object[] itemsField;
    
    private string idField;
    
    private string indexField;
    
    private string allowField;
    
    private string disallowField;
    
    private string preferField;
    
    private float speedField;
    
    private float frictionField;
    
    private bool frictionFieldSpecified;
    
    private float lengthField;
    
    private float endOffsetField;
    
    private bool endOffsetFieldSpecified;
    
    private float widthField;
    
    private bool widthFieldSpecified;
    
    private boolType accelerationField;
    
    private bool accelerationFieldSpecified;
    
    private string shapeField;
    
    private boolType customShapeField;
    
    private bool customShapeFieldSpecified;
    
    private string typeField;
    
    private string changeRightField;
    
    private string changeLeftField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("neigh", typeof(neighType))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(paramType))]
    [System.Xml.Serialization.XmlElementAttribute("stopOffset", typeof(stopOffsetType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disallow {
        get {
            return this.disallowField;
        }
        set {
            this.disallowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefer {
        get {
            return this.preferField;
        }
        set {
            this.preferField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float friction {
        get {
            return this.frictionField;
        }
        set {
            this.frictionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool frictionSpecified {
        get {
            return this.frictionFieldSpecified;
        }
        set {
            this.frictionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float endOffset {
        get {
            return this.endOffsetField;
        }
        set {
            this.endOffsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endOffsetSpecified {
        get {
            return this.endOffsetFieldSpecified;
        }
        set {
            this.endOffsetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthSpecified {
        get {
            return this.widthFieldSpecified;
        }
        set {
            this.widthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType acceleration {
        get {
            return this.accelerationField;
        }
        set {
            this.accelerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool accelerationSpecified {
        get {
            return this.accelerationFieldSpecified;
        }
        set {
            this.accelerationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType customShape {
        get {
            return this.customShapeField;
        }
        set {
            this.customShapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool customShapeSpecified {
        get {
            return this.customShapeFieldSpecified;
        }
        set {
            this.customShapeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeRight {
        get {
            return this.changeRightField;
        }
        set {
            this.changeRightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeLeft {
        get {
            return this.changeLeftField;
        }
        set {
            this.changeLeftField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class edgeType {
    
    private object[] itemsField;
    
    private string idField;
    
    private edgeTypeFunction functionField;
    
    private bool functionFieldSpecified;
    
    private string fromField;
    
    private string toField;
    
    private string nameField;
    
    private string priorityField;
    
    private float lengthField;
    
    private bool lengthFieldSpecified;
    
    private string bidiField;
    
    private string typeField;
    
    private string shapeField;
    
    private string distanceField;
    
    private spreadTypeType spreadTypeField;
    
    private bool spreadTypeFieldSpecified;
    
    private string crossingEdgesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lane", typeof(laneType))]
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(paramType))]
    [System.Xml.Serialization.XmlElementAttribute("stopOffset", typeof(stopOffsetType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public edgeTypeFunction function {
        get {
            return this.functionField;
        }
        set {
            this.functionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool functionSpecified {
        get {
            return this.functionFieldSpecified;
        }
        set {
            this.functionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lengthSpecified {
        get {
            return this.lengthFieldSpecified;
        }
        set {
            this.lengthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bidi {
        get {
            return this.bidiField;
        }
        set {
            this.bidiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public spreadTypeType spreadType {
        get {
            return this.spreadTypeField;
        }
        set {
            this.spreadTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool spreadTypeSpecified {
        get {
            return this.spreadTypeFieldSpecified;
        }
        set {
            this.spreadTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crossingEdges {
        get {
            return this.crossingEdgesField;
        }
        set {
            this.crossingEdgesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum edgeTypeFunction {
    
    /// <remarks/>
    normal,
    
    /// <remarks/>
    @internal,
    
    /// <remarks/>
    connector,
    
    /// <remarks/>
    crossing,
    
    /// <remarks/>
    walkingarea,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
public enum spreadTypeType {
    
    /// <remarks/>
    center,
    
    /// <remarks/>
    roadCenter,
    
    /// <remarks/>
    right,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class laneTypeType {
    
    private restrictionType[] itemsField;
    
    private int indexField;
    
    private string allowField;
    
    private string disallowField;
    
    private string speedField;
    
    private string widthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("restriction")]
    public restrictionType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disallow {
        get {
            return this.disallowField;
        }
        set {
            this.disallowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class restrictionType {
    
    private string vClassField;
    
    private string speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vClass {
        get {
            return this.vClassField;
        }
        set {
            this.vClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mesoType {
    
    private float tauffField;
    
    private bool tauffFieldSpecified;
    
    private float taufjField;
    
    private bool taufjFieldSpecified;
    
    private float taujfField;
    
    private bool taujfFieldSpecified;
    
    private float taujjField;
    
    private bool taujjFieldSpecified;
    
    private string jamThresholdField;
    
    private boolType junctionControlField;
    
    private bool junctionControlFieldSpecified;
    
    private float tlsPenaltyField;
    
    private bool tlsPenaltyFieldSpecified;
    
    private float tlsFlowPenaltyField;
    
    private bool tlsFlowPenaltyFieldSpecified;
    
    private float minorPenaltyField;
    
    private bool minorPenaltyFieldSpecified;
    
    private boolType overtakingField;
    
    private bool overtakingFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float tauff {
        get {
            return this.tauffField;
        }
        set {
            this.tauffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tauffSpecified {
        get {
            return this.tauffFieldSpecified;
        }
        set {
            this.tauffFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float taufj {
        get {
            return this.taufjField;
        }
        set {
            this.taufjField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool taufjSpecified {
        get {
            return this.taufjFieldSpecified;
        }
        set {
            this.taufjFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float taujf {
        get {
            return this.taujfField;
        }
        set {
            this.taujfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool taujfSpecified {
        get {
            return this.taujfFieldSpecified;
        }
        set {
            this.taujfFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float taujj {
        get {
            return this.taujjField;
        }
        set {
            this.taujjField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool taujjSpecified {
        get {
            return this.taujjFieldSpecified;
        }
        set {
            this.taujjFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jamThreshold {
        get {
            return this.jamThresholdField;
        }
        set {
            this.jamThresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType junctionControl {
        get {
            return this.junctionControlField;
        }
        set {
            this.junctionControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool junctionControlSpecified {
        get {
            return this.junctionControlFieldSpecified;
        }
        set {
            this.junctionControlFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float tlsPenalty {
        get {
            return this.tlsPenaltyField;
        }
        set {
            this.tlsPenaltyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tlsPenaltySpecified {
        get {
            return this.tlsPenaltyFieldSpecified;
        }
        set {
            this.tlsPenaltyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float tlsFlowPenalty {
        get {
            return this.tlsFlowPenaltyField;
        }
        set {
            this.tlsFlowPenaltyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tlsFlowPenaltySpecified {
        get {
            return this.tlsFlowPenaltyFieldSpecified;
        }
        set {
            this.tlsFlowPenaltyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float minorPenalty {
        get {
            return this.minorPenaltyField;
        }
        set {
            this.minorPenaltyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minorPenaltySpecified {
        get {
            return this.minorPenaltyFieldSpecified;
        }
        set {
            this.minorPenaltyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType overtaking {
        get {
            return this.overtakingField;
        }
        set {
            this.overtakingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool overtakingSpecified {
        get {
            return this.overtakingFieldSpecified;
        }
        set {
            this.overtakingFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class typeType {
    
    private object[] itemsField;
    
    private string idField;
    
    private string allowField;
    
    private string disallowField;
    
    private int priorityField;
    
    private bool priorityFieldSpecified;
    
    private int numLanesField;
    
    private bool numLanesFieldSpecified;
    
    private string speedField;
    
    private boolType discardField;
    
    private bool discardFieldSpecified;
    
    private boolType onewayField;
    
    private bool onewayFieldSpecified;
    
    private string widthField;
    
    private float widthResolutionField;
    
    private bool widthResolutionFieldSpecified;
    
    private float maxWidthField;
    
    private bool maxWidthFieldSpecified;
    
    private float minWidthField;
    
    private bool minWidthFieldSpecified;
    
    private string sidewalkWidthField;
    
    private string bikeLaneWidthField;
    
    private typeTypeSpreadType spreadTypeField;
    
    private bool spreadTypeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("laneType", typeof(laneTypeType))]
    [System.Xml.Serialization.XmlElementAttribute("meso", typeof(mesoType))]
    [System.Xml.Serialization.XmlElementAttribute("restriction", typeof(restrictionType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disallow {
        get {
            return this.disallowField;
        }
        set {
            this.disallowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool prioritySpecified {
        get {
            return this.priorityFieldSpecified;
        }
        set {
            this.priorityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numLanes {
        get {
            return this.numLanesField;
        }
        set {
            this.numLanesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numLanesSpecified {
        get {
            return this.numLanesFieldSpecified;
        }
        set {
            this.numLanesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType discard {
        get {
            return this.discardField;
        }
        set {
            this.discardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool discardSpecified {
        get {
            return this.discardFieldSpecified;
        }
        set {
            this.discardFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType oneway {
        get {
            return this.onewayField;
        }
        set {
            this.onewayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onewaySpecified {
        get {
            return this.onewayFieldSpecified;
        }
        set {
            this.onewayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float widthResolution {
        get {
            return this.widthResolutionField;
        }
        set {
            this.widthResolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthResolutionSpecified {
        get {
            return this.widthResolutionFieldSpecified;
        }
        set {
            this.widthResolutionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float maxWidth {
        get {
            return this.maxWidthField;
        }
        set {
            this.maxWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxWidthSpecified {
        get {
            return this.maxWidthFieldSpecified;
        }
        set {
            this.maxWidthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float minWidth {
        get {
            return this.minWidthField;
        }
        set {
            this.minWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minWidthSpecified {
        get {
            return this.minWidthFieldSpecified;
        }
        set {
            this.minWidthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sidewalkWidth {
        get {
            return this.sidewalkWidthField;
        }
        set {
            this.sidewalkWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bikeLaneWidth {
        get {
            return this.bikeLaneWidthField;
        }
        set {
            this.bikeLaneWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public typeTypeSpreadType spreadType {
        get {
            return this.spreadTypeField;
        }
        set {
            this.spreadTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool spreadTypeSpecified {
        get {
            return this.spreadTypeFieldSpecified;
        }
        set {
            this.spreadTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum typeTypeSpreadType {
    
    /// <remarks/>
    center,
    
    /// <remarks/>
    roadCenter,
    
    /// <remarks/>
    right,
}
